---
moniker: 8E8A4F6C-C-UE1
envName: dev
logLevel: debug
lambda-hello-provisionedConcurrency: 1
lambda-hello-reservedConcurrency: 1
#fisLayer: arn:aws:lambda:us-east-1:975050054544:layer:aws-fis-extension-x86_64:99
fisLayer: arn:aws:lambda:us-east-1:211125607513:layer:aws-fis-extension-x86_64:103

