Resources:
  ChaosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${self:service}-config-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: 'adsk:moniker'
          Value: ${self:custom.config.moniker}

  ChaosBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ChaosBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSSLRequestsOnlyICS
            Principal: '*'
            Effect: Deny
            Action:
              - s3:*
            Resource:
              - !Sub 'arn:aws:s3:::${self:service}-config-${AWS::Region}-${AWS::AccountId}'
              - !Sub 'arn:aws:s3:::${self:service}-config-${AWS::Region}-${AWS::AccountId}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

